[package]
name = "dmitool"
version = "0.1.0"
authors = ["Noah Meyerhans <frodo@morgul.net>"]
edition = "2018"
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
